// ============================================================
// deinterleaver.v -- block (matrix) de-interleaver
//
// Port of spectracuda's BlockInterleaver (spectracuda/interleaver/block.py):
// write an M x N grid row-major, read it column-major.
//     M    = rows (1 + floor(sqrt(n_units)) by default)
//     N    = ceil(n_units / M)
//     perm = column-major read of grid[r][c] = r*N + c, dropping any
//            cell >= n_units (the grid over-covers; the excess cells are
//            virtual and are skipped, NOT zero-padded)
// `perm[i]` is which ORIGINAL unit ends up at output position i
// (interleaver/base.py:94), so de-interleaving writes arriving unit i to
// address perm[i] and reads out linearly.
//
// THIS IS NOT DECORATION. abhi/pluto_rx_standalone_v2.py's PHY_KWARGS
// records the block interleaver root-causing real 1024-byte over-the-air
// packet losses: interference arrives as a burst of Viterbi errors
// concentrated in a narrow byte range, which blows Reed-Solomon's
// per-codeword error budget. Block interleaving spreads that burst across
// many codewords. unit_bits=8 matches rs_m8's byte symbol size --
// bit-granularity interleaving of a byte-oriented code was MEASURED to
// make bursts worse, not better.
//
// NO PERMUTATION ROM, unlike the channel estimator's interpolation table.
// n_bits varies per frame (framing/packetizer.py:92-96 caches interleaver
// instances by n_bits for exactly that reason), so a fixed table cannot
// serve. The permutation has closed form, so it is GENERATED by two
// counters instead -- and with a row-base accumulator it needs no
// multiplier either.
//
// M and N are inputs rather than computed here: deriving M needs an
// integer square root and N a division, both once per frame, and both
// belong with whatever decodes the header rather than in the datapath.
// ============================================================
`timescale 1ns / 1ps

module deinterleaver #(
    parameter integer UNIT_W    = 8,      // unit_bits; 8 for rs_m8
    parameter integer MAX_UNITS = 4096,
    parameter integer CNT_W     = 13      // >= log2(MAX_UNITS)+1
)(
    input  wire                clk,
    input  wire                rst,

    // Per-frame geometry, held stable while a block streams through.
    input  wire [CNT_W-1:0]    n_units,
    input  wire [CNT_W-1:0]    rows,      // M
    input  wire [CNT_W-1:0]    cols,      // N
    input  wire                start,     // pulse before the first unit

    input  wire [UNIT_W-1:0]   in_unit,
    input  wire                in_valid,
    output wire                in_ready,  // low while skipping virtual cells

    output reg  [UNIT_W-1:0]   out_unit,
    output reg                 out_valid,
    output reg                 out_last
);

    localparam integer ADDR_W = $clog2(MAX_UNITS);

    reg [UNIT_W-1:0] mem [0:MAX_UNITS-1];

    // Explicit narrowing to the memory's address width. The counters are
    // one bit wider so they can hold n_units itself for the end-of-block
    // comparisons; the addresses are provably in range (writes are gated
    // on idx < n_units, reads run 0..n_units-1), so this is a sized
    // slice rather than a waived truncation warning.

    // ---- write side: generate perm[i] ----
    reg [CNT_W-1:0] r, c, row_base, wr_i;
    reg             filling;

    // idx = r*N + c, tracked as an accumulator so no multiplier is needed.
    wire [CNT_W-1:0] idx   = row_base + c;
    wire             valid_cell = (idx < n_units);

    // Input is only accepted on a real cell. The skipped cells are the
    // grid's virtual padding -- at most M-1 of them per frame, so the
    // stall is negligible.
    assign in_ready = filling && valid_cell;

    // ---- read side ----
    reg [CNT_W-1:0] rd_i;
    reg             draining;

    always @(posedge clk) begin
        if (rst) begin
            r <= 0; c <= 0; row_base <= 0; wr_i <= 0;
            rd_i <= 0; filling <= 1'b0; draining <= 1'b0;
            out_valid <= 1'b0; out_last <= 1'b0;
        end else begin
            out_valid <= 1'b0;
            out_last  <= 1'b0;

            if (start) begin
                r <= 0; c <= 0; row_base <= 0; wr_i <= 0;
                rd_i <= 0; filling <= 1'b1; draining <= 1'b0;
            end else if (filling) begin
                if (valid_cell) begin
                    if (in_valid) begin
                        mem[idx[ADDR_W-1:0]] <= in_unit;
                        wr_i <= wr_i + 1'b1;
                        if (wr_i == n_units - 1) begin
                            filling  <= 1'b0;
                            draining <= 1'b1;
                        end
                    end
                end
                // Advance the column-major walk. On a virtual cell this
                // runs without consuming input, which is what in_ready
                // is telling the producer.
                if (valid_cell ? in_valid : 1'b1) begin
                    if (r == rows - 1) begin
                        r <= 0; row_base <= 0; c <= c + 1'b1;
                    end else begin
                        r <= r + 1'b1; row_base <= row_base + cols;
                    end
                end
            end else if (draining) begin
                out_unit  <= mem[rd_i[ADDR_W-1:0]];
                out_valid <= 1'b1;
                out_last  <= (rd_i == n_units - 1);
                if (rd_i == n_units - 1) begin
                    draining <= 1'b0;
                    rd_i <= 0;
                end else begin
                    rd_i <= rd_i + 1'b1;
                end
            end
        end
    end
endmodule
