"""Stimulus for the LS channel-estimator test.

Inputs are the received reference bins straight from spectracuda's own
frame, scaled into the RTL's integer domain in one place as with every
other block.

Note the reference bins are the TRAINING SYMBOL's 224 known subcarriers,
not the 8 pilot tones -- Ofdm configures LSChannelEstimator with
pilot_indices=_train_known_indices. Reading them off ofdm.grid instead
produced an 8-entry table that quietly disagreed with the golden model.
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

IN_SCALE = 1 << 12     # pilots are ~unit magnitude; Q12 keeps headroom
H_SCALE = 1 << 12


def load_iq(path):
    v = []
    with open(path) as f:
        for line in f:
            p = line.split()
            if len(p) == 2:
                v.append((float(p[0]), float(p[1])))
    return np.array(v, dtype=np.float64)


def main() -> None:
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # fpga/
    case = sys.argv[1] if len(sys.argv) > 1 else "ce_snr20_s07"
    src = os.path.normpath(os.path.join(here, "fixtures", "blocks", case))
    out = os.path.join(here, "build")
    os.makedirs(out, exist_ok=True)

    with open(os.path.join(src, "ce_meta.json")) as f:
        meta = json.load(f)

    pil = load_iq(os.path.join(src, "ce_pilots.txt"))
    code = np.round(pil * IN_SCALE).astype(np.int64)
    code = np.clip(code, -(1 << 19), (1 << 19) - 1)
    with open(os.path.join(out, "ce_stimulus.hex"), "w") as f:
        for i, q in code:
            f.write(f"{((int(i) & 0xFFFFF) << 20) | (int(q) & 0xFFFFF):010x}\n")

    ref = load_iq(os.path.join(src, "ce_expected.txt")) * H_SCALE
    np.savetxt(os.path.join(out, "ce_ref.txt"), ref, fmt="%.4f")

    with open(os.path.join(out, "ce_params.vh"), "w") as f:
        f.write(f"// GENERATED by fpga/sim/gen_ce_stimulus.py from {case}\n")
        f.write(f'`define CE_STIM_PATH "{os.path.join(out, "ce_stimulus.hex")}"\n')
        f.write(f'`define CE_OUT_PATH "{os.path.join(out, "ce_out.txt")}"\n')
        f.write(f"`define CE_N_IN {len(code)}\n")
        f.write(f"`define CE_N_BINS {meta['n_fft']}\n")

    print(f"  case {case}: {len(code)} refs -> {meta['n_fft']} bins  "
          f"in_peak={np.max(np.abs(code)):.0f}  ref_peak={np.max(np.abs(ref)):.0f}")


if __name__ == "__main__":
    main()
