"""Stimulus + expected bits for viterbi_dec.v, straight from spectracuda.

Never reimplements the code: it calls ConvolutionalCode.encode(), the
same object the Pluto link uses, so the wire order (out1 then out2) and
the zero-tail termination come from the golden model rather than from
this script's idea of them.

Errors are injected at a RATE, not at hand-picked positions. A decoder
that is subtly wrong -- swapped polynomials, off-by-one traceback --
still decodes a clean stream perfectly, so a zero-error case proves
almost nothing. The interesting cases are at the error rates the link
actually sees.
"""
from __future__ import annotations

import os
import sys

import numpy as np

# The pinned golden model, NOT the working-tree spectracuda -- see golden_ref.py.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import golden_ref  # noqa: E402
golden_ref.use()

from spectracuda.fec.viterbi import ConvolutionalCode  # noqa: E402


def main() -> None:
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # fpga/
    out = os.path.join(here, "build")
    os.makedirs(out, exist_ok=True)

    n_bits = int(sys.argv[1]) if len(sys.argv) > 1 else 512
    ber = float(sys.argv[2]) if len(sys.argv) > 2 else 0.0
    seed = int(sys.argv[3]) if len(sys.argv) > 3 else 0

    rng = np.random.default_rng(seed)
    bits = rng.integers(0, 2, size=(1, n_bits)).astype(np.uint8)

    code = ConvolutionalCode()
    enc = np.asarray(code.encode(bits))[0].astype(np.uint8)

    rx = enc.copy()
    if ber > 0.0:
        flip = rng.random(rx.shape) < ber
        rx[flip] ^= 1
        n_flipped = int(flip.sum())
    else:
        n_flipped = 0

    # What Python's own decoder makes of this exact received stream --
    # not the transmitted bits. At a nonzero error rate the decoder may
    # legitimately get some wrong, and the RTL is required to reproduce
    # PYTHON, not to beat it.
    dec = np.asarray(code.decode(rx[None, :]))[0].astype(np.uint8)

    n_sym = enc.size // 2
    with open(os.path.join(out, "viterbi_stimulus.hex"), "w") as f:
        for i in range(n_sym):
            # sym[0] = out1 (G1, 0o171), sym[1] = out2 (G2, 0o133)
            f.write(f"{(int(rx[2 * i + 1]) << 1) | int(rx[2 * i]):01x}\n")

    with open(os.path.join(out, "viterbi_expected.txt"), "w") as f:
        for b in dec:
            f.write(f"{int(b)}\n")

    # Transmitted bits, so a disagreement with Python can be scored as
    # "RTL is worse" or merely "RTL is different" -- past the code's
    # breakdown point the two are not the same claim.
    with open(os.path.join(out, "viterbi_tx.txt"), "w") as f:
        for b in bits[0]:
            f.write(f"{int(b)}\n")

    with open(os.path.join(out, "vit_tb_params.vh"), "w") as f:
        f.write(f"// GENERATED by fpga/sim/gen_viterbi_stimulus.py\n")
        f.write(f'`define VIT_STIM_PATH "{os.path.join(out, "viterbi_stimulus.hex")}"\n')
        f.write(f'`define VIT_OUT_PATH "{os.path.join(out, "viterbi_out.txt")}"\n')
        f.write(f"`define VIT_NSYM {n_sym}\n")
        f.write(f"`define VIT_NBITS {n_bits}\n")

    agree = int((dec == bits[0]).sum())
    print(f"  n_bits={n_bits} ber={ber} seed={seed}: {n_sym} symbols, "
          f"{n_flipped} bits flipped, python decoded {agree}/{n_bits} correct")


if __name__ == "__main__":
    main()
