"""Test vectors for cordic_vec: (x, y) pairs and numpy's atan2 answer.

Sweeps the full circle rather than the first quadrant, because the
quadrant folding (negative x is rotated by half a turn and the half turn
added back) is exactly the part most likely to be wrong, and a
first-quadrant test would pass with it entirely broken.

Includes the degenerate cases -- axes and origin -- for the same reason.
Angles are in TURNS, matching the block; see fpga/gen/emit_rtl.py.
"""
from __future__ import annotations

import os

import numpy as np

DATA_W = 20
ANGLE_W = 16
AMP = (1 << (DATA_W - 2))     # leave headroom below full scale


def main() -> None:
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # fpga/
    out = os.path.join(here, "build")
    os.makedirs(out, exist_ok=True)

    xs, ys = [], []
    # Full circle, deliberately off-grid so no test angle lands exactly
    # on a CORDIC breakpoint.
    for k in range(360):
        th = 2 * np.pi * (k + 0.37) / 360.0
        xs.append(int(round(AMP * np.cos(th))))
        ys.append(int(round(AMP * np.sin(th))))
    # Axes and origin.
    for x, y in [(AMP, 0), (-AMP, 0), (0, AMP), (0, -AMP), (0, 0),
                 (1, 0), (-1, 0), (0, 1), (0, -1)]:
        xs.append(x)
        ys.append(y)
    # Very small magnitudes: the estimator sees these at low SNR.
    for k in range(16):
        th = 2 * np.pi * k / 16
        xs.append(int(round(7 * np.cos(th))))
        ys.append(int(round(7 * np.sin(th))))

    mask = (1 << DATA_W) - 1
    with open(os.path.join(out, "cordic_stim.hex"), "w") as f:
        for x, y in zip(xs, ys):
            f.write(f"{((x & mask) << DATA_W) | (y & mask):010x}\n")

    with open(os.path.join(out, "cordic_expected.txt"), "w") as f:
        for x, y in zip(xs, ys):
            turns = np.arctan2(float(y), float(x)) / (2 * np.pi)
            code = int(np.floor(turns * (1 << ANGLE_W) + 0.5))
            # Wrap into the signed ANGLE_W range, matching the block's
            # two's-complement phase word.
            code = ((code + (1 << (ANGLE_W - 1))) % (1 << ANGLE_W)) - (1 << (ANGLE_W - 1))
            f.write(f"{x} {y} {code}\n")

    with open(os.path.join(out, "cordic_params.vh"), "w") as f:
        f.write("// GENERATED by fpga/sim/gen_cordic_vectors.py\n")
        f.write(f"`define CORDIC_N_VEC {len(xs)}\n")
    print(f"  {len(xs)} vectors -> build/cordic_stim.hex")


if __name__ == "__main__":
    main()
