"""Stimulus for the CFO integration test.

Python's P is computed on float samples (|s| <= 0.9); the RTL computes it
from int16, so the RTL's P is the float one scaled by FULL_SCALE^2. That
factor is applied here, in one place, rather than being left for the
testbench to get wrong.

The scaling does not actually matter to the ESTIMATOR -- cfo_estimate
normalizes P by a common power of two and only its components' ratio
reaches the CORDIC -- but feeding a realistically-sized value is what
makes the normalizer's leading-bit search part of the test rather than
something exercised only by accident.
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

FULL_SCALE = (1 << 15) - 1
ACC_W = 48
ANGLE_W = 16


def main() -> None:
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # fpga/
    case = sys.argv[1] if len(sys.argv) > 1 else "cfo_snr20_s07"
    src = os.path.normpath(os.path.join(here, "fixtures", "blocks", case))
    out = os.path.join(here, "build")
    os.makedirs(out, exist_ok=True)

    with open(os.path.join(src, "cfo_meta.json")) as f:
        meta = json.load(f)

    def load_iq(name):
        v = []
        with open(os.path.join(src, name)) as f:
            for line in f:
                p = line.split()
                if len(p) == 2:
                    v.append((float(p[0]), float(p[1])))
        return np.array(v, dtype=np.float64)

    rx = load_iq("cfo_rx.txt")
    scaled = rx * FULL_SCALE
    code = np.where(scaled >= 0, np.floor(scaled + 0.5), np.ceil(scaled - 0.5))
    code = np.clip(code, -32768, 32767).astype(np.int64)
    with open(os.path.join(out, "cfo_stimulus.hex"), "w") as f:
        for i, q in code:
            f.write(f"{((int(i) & 0xFFFF) << 16) | (int(q) & 0xFFFF):08x}\n")

    p_re = int(round(meta["p_re"] * FULL_SCALE * FULL_SCALE))
    p_im = int(round(meta["p_im"] * FULL_SCALE * FULL_SCALE))
    mask = (1 << ACC_W) - 1

    ang = meta["expected_angle_turns"]
    ang_code = int(np.floor(ang * (1 << ANGLE_W) + 0.5))
    ang_code = ((ang_code + (1 << (ANGLE_W - 1))) % (1 << ANGLE_W)) - (1 << (ANGLE_W - 1))

    # P goes in a FILE, not a `define. It was a define first, and that
    # silently broke the multi-case sweep: the value is baked in at
    # compile time, so every case ran against whichever P the binary was
    # last built with while the checker compared against the new case's
    # expectation. Twelve confident failures, none of them real.
    with open(os.path.join(out, "cfo_p.hex"), "w") as f:
        f.write(f"{p_re & mask:012x}\n{p_im & mask:012x}\n")

    with open(os.path.join(out, "cfo_params.vh"), "w") as f:
        f.write(f"// GENERATED by fpga/sim/gen_cfo_stimulus.py from {case}\n")
        f.write(f"// N_SAMPLES is the only compile-time value; it sizes an\n")
        f.write(f"// array. Everything else is read at run time.\n")
        f.write(f"`define CFO_N_SAMPLES {max(len(code), 8192)}\n")
        f.write(f"`define CFO_N_ACTUAL {len(code)}\n")

    with open(os.path.join(out, "cfo_expected.json"), "w") as f:
        json.dump({
            "case": case,
            "n_samples": len(code),
            "expected_angle_code": ang_code,
            "expected_angle_turns": ang,
            "expected_cfo": meta["expected_cfo"],
            "p_re_scaled": p_re, "p_im_scaled": p_im,
        }, f, indent=2)

    # Reference corrected samples, in the same int16 domain the RTL emits.
    corr = load_iq("cfo_corrected.txt") * FULL_SCALE
    np.savetxt(os.path.join(out, "cfo_ref_corrected.txt"), corr, fmt="%.4f")

    print(f"  case {case}: {len(code)} samples, "
          f"P=({p_re}, {p_im}), angle_code={ang_code}")


if __name__ == "__main__":
    main()
