"""Stimulus for one CRC case."""
from __future__ import annotations
import json, os, sys


def main() -> None:
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # fpga/
    k = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    src = os.path.normpath(os.path.join(here, "fixtures", "blocks", "crc"))
    with open(os.path.join(src, "crc_meta.json")) as f:
        meta = json.load(f)
    msgs = [l.split() for l in open(os.path.join(src, "crc_msgs.txt"))]
    msg, exp = msgs[k], meta["cases"][k]
    out = os.path.join(here, "build"); os.makedirs(out, exist_ok=True)

    # A zero-length message still needs a file $readmemh can open; one
    # dummy word that the testbench never clocks in.
    with open(os.path.join(out, "crc_stim.hex"), "w") as f:
        f.write("\n".join(msg) + "\n" if msg else "00\n")
    with open(os.path.join(out, "crc_tb_params.vh"), "w") as f:
        f.write(f"// GENERATED by gen_crc_stimulus.py, case {k}\n")
        f.write(f'`define CR_STIM_PATH "{os.path.join(out, "crc_stim.hex")}"\n')
        f.write(f'`define CR_OUT_PATH "{os.path.join(out, "crc_out.txt")}"\n')
        f.write(f"`define CR_N {len(msg)}\n")
        f.write(f"`define CR_NMEM {max(len(msg), 1)}\n")
    with open(os.path.join(out, "crc_expected.txt"), "w") as f:
        f.write(f"{exp['crc']}\n")
    print(f"  case {k}: {exp['len']:>5} bytes -> expect 0x{exp['crc']:04x}")


if __name__ == "__main__":
    main()
