"""Test vectors for cordic_rot: (x, y, z) and numpy's rotated answer.

Sweeps z over the FULL turn, not just the convergence range, because the
quadrant fold (negate the vector, add half a turn to z) is the part most
likely to be wrong and a narrow sweep would pass with it broken. Also
sweeps the input vector's own angle, so a fold bug cannot hide behind a
vector that happens to be symmetric.
"""
from __future__ import annotations

import os

import numpy as np

DATA_W = 16
ANGLE_W = 16
AMP = 12000          # below full scale: CORDIC swings above the input mid-rotation


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "build")
    os.makedirs(out, exist_ok=True)

    rows = []
    for zk in range(64):
        z_turns = (zk + 0.31) / 64.0 - 0.5           # full turn, off-grid
        zc = int(np.floor(z_turns * (1 << ANGLE_W) + 0.5))
        zc = ((zc + (1 << (ANGLE_W - 1))) % (1 << ANGLE_W)) - (1 << (ANGLE_W - 1))
        for vk in range(8):
            th = 2 * np.pi * (vk + 0.19) / 8.0
            x = int(round(AMP * np.cos(th)))
            y = int(round(AMP * np.sin(th)))
            ang = 2 * np.pi * (zc / (1 << ANGLE_W))
            xr = x * np.cos(ang) - y * np.sin(ang)
            yr = x * np.sin(ang) + y * np.cos(ang)
            rows.append((x, y, zc, xr, yr))

    m16 = (1 << DATA_W) - 1
    ma = (1 << ANGLE_W) - 1
    with open(os.path.join(out, "rot_stim.hex"), "w") as f:
        for x, y, z, _, _ in rows:
            f.write(f"{((x & m16) << 32) | ((y & m16) << 16) | (z & ma):012x}\n")
    with open(os.path.join(out, "rot_expected.txt"), "w") as f:
        for x, y, z, xr, yr in rows:
            f.write(f"{x} {y} {z} {xr:.4f} {yr:.4f}\n")
    with open(os.path.join(out, "rot_params.vh"), "w") as f:
        f.write("// GENERATED by hls/rtl/gen_rot_vectors.py\n")
        f.write(f"`define ROT_N_VEC {len(rows)}\n")
    print(f"  {len(rows)} vectors -> build/rot_stim.hex")


if __name__ == "__main__":
    main()
