"""Stimulus for the demapper test. Q12, matching mmse_eq's output."""
from __future__ import annotations
import json, os, sys
import numpy as np

Q = 1 << 12
CODE = {"qpsk": 0, "qam16": 1, "qam64": 2}


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    scheme = sys.argv[1] if len(sys.argv) > 1 else "qpsk"
    src = os.path.normpath(os.path.join(here, "..", "golden", f"dm_{scheme}"))
    out = os.path.join(here, "build"); os.makedirs(out, exist_ok=True)
    with open(os.path.join(src, "dm_meta.json")) as f:
        meta = json.load(f)

    v = []
    with open(os.path.join(src, "dm_sym.txt")) as f:
        for line in f:
            p = line.split()
            if len(p) == 2:
                v.append((float(p[0]), float(p[1])))
    sym = np.round(np.array(v) * Q).astype(np.int64)
    lim = 1 << 17
    sym = np.clip(sym, -lim, lim - 1)
    with open(os.path.join(out, "dm_stimulus.hex"), "w") as f:
        for re_, im_ in sym:
            f.write(f"{((int(re_) & 0x3FFFF) << 18) | (int(im_) & 0x3FFFF):09x}\n")

    with open(os.path.join(out, "dm_tb_params.vh"), "w") as f:
        f.write(f"// GENERATED by hls/rtl/gen_dm_stimulus.py for {scheme}\n")
        f.write(f'`define DM_STIM_PATH "{os.path.join(out, "dm_stimulus.hex")}"\n')
        f.write(f'`define DM_OUT_PATH "{os.path.join(out, "dm_out.txt")}"\n')
        f.write(f"`define DM_N {len(sym)}\n")
        f.write(f"`define DM_SCHEME {CODE[scheme]}\n")
        f.write(f"`define DM_BPS {meta['bits_per_symbol']}\n")
    print(f"  {scheme}: {len(sym)} symbols, {meta['bits_per_symbol']} bits each")


if __name__ == "__main__":
    main()
