"""Convert the float golden IQ vectors into int16 hex for $readmemh.

The RTL works in the same format the hardware delivers: 16-bit signed I
and Q (see spectracuda's own Pluto path -- pyadi returns int16-ranged
values, and `examples/drone_tui/pluto.py` scales to 2**13 on transmit).
The float golden files are the reference; this is the only place the
conversion happens, so the RTL and HLS testbenches cannot disagree about
scaling by accident.

Full scale is 2**15-1. Values are rounded half-away-from-zero and
saturated, matching ApFixed's AP_RND/AP_SAT -- NOT numpy's round-half-to-
even, which would differ by an LSB on exact .5 cases.
"""
from __future__ import annotations

import os
import sys

import numpy as np

FULL_SCALE = (1 << 15) - 1


def convert(src: str, dst: str) -> int:
    vals = []
    with open(src) as f:
        for line in f:
            parts = line.split()
            if len(parts) == 2:
                vals.append((float(parts[0]), float(parts[1])))
    arr = np.array(vals, dtype=np.float64)
    scaled = arr * FULL_SCALE
    code = np.where(scaled >= 0, np.floor(scaled + 0.5), np.ceil(scaled - 0.5))
    code = np.clip(code, -32768, 32767).astype(np.int64)
    with open(dst, "w") as f:
        for i, q in code:
            # {I[15:0], Q[15:0]} in one 32-bit word, matching openofdm's
            # sample_in[31:16]=I / sample_in[15:0]=Q convention.
            word = ((int(i) & 0xFFFF) << 16) | (int(q) & 0xFFFF)
            f.write(f"{word:08x}\n")
    return len(code)


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    golden = os.path.normpath(os.path.join(here, "..", "golden"))
    out = os.path.join(here, "build")
    os.makedirs(out, exist_ok=True)
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(golden, "sc_sync_rx.txt")
    dst = os.path.join(out, "stimulus.hex")
    n = convert(src, dst)

    # Emit the count as a define rather than letting the testbench detect
    # end-of-data by scanning for x. Verilator runs 2-state by default, so
    # an untouched array entry reads as 0 -- indistinguishable from a real
    # silent sample, and the golden capture opens with 200 of those. This
    # is deterministic in every simulator.
    with open(os.path.join(out, "stim_params.vh"), "w") as f:
        f.write("// GENERATED by hls/rtl/gen_stimulus.py -- do not edit\n")
        f.write(f"`define N_SAMPLES {n}\n")
    print(f"  {src} -> {dst}  ({n} samples)")


if __name__ == "__main__":
    main()
