"""Stimulus for the MMSE equalizer test.

rx, H and y are all Q12, matching ls_chanest's output format, so the two
blocks connect without a rescale between them.
"""
from __future__ import annotations

import json, os, sys
import numpy as np

Q = 1 << 12


def load_iq(path):
    v = []
    with open(path) as f:
        for line in f:
            p = line.split()
            if len(p) == 2:
                v.append((float(p[0]), float(p[1])))
    return np.array(v, dtype=np.float64)


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    case = sys.argv[1] if len(sys.argv) > 1 else "eq_snr20_s07"
    src = os.path.normpath(os.path.join(here, "..", "golden", case))
    out = os.path.join(here, "build"); os.makedirs(out, exist_ok=True)
    with open(os.path.join(src, "eq_meta.json")) as f:
        meta = json.load(f)

    rx = np.round(load_iq(os.path.join(src, "eq_rx.txt")) * Q).astype(np.int64)
    h = np.round(load_iq(os.path.join(src, "eq_h.txt")) * Q).astype(np.int64)
    lim = 1 << 17
    rx = np.clip(rx, -lim, lim - 1); h = np.clip(h, -lim, lim - 1)

    with open(os.path.join(out, "eq_stimulus.hex"), "w") as f:
        for (rr, ri), (hr, hi) in zip(rx, h):
            w = ((int(rr) & 0x3FFFF) << 54) | ((int(ri) & 0x3FFFF) << 36) \
                | ((int(hr) & 0x3FFFF) << 18) | (int(hi) & 0x3FFFF)
            f.write(f"{w:018x}\n")

    # Reference recomputed from the QUANTIZED rx and H, so the score
    # isolates the equalizer's own error rather than folding in the input
    # quantization that both sides share.
    rxc = (rx[:, 0] + 1j * rx[:, 1]) / Q
    hc = (h[:, 0] + 1j * h[:, 1]) / Q
    y = rxc * np.conj(hc) / (np.abs(hc) ** 2 + meta["noise_var"])
    np.savetxt(os.path.join(out, "eq_ref.txt"),
               np.column_stack([y.real * Q, y.imag * Q]), fmt="%.4f")

    with open(os.path.join(out, "eq_tb_params.vh"), "w") as f:
        f.write(f"// GENERATED by hls/rtl/gen_eq_stimulus.py from {case}\n")
        f.write(f'`define EQ_STIM_PATH "{os.path.join(out, "eq_stimulus.hex")}"\n')
        f.write(f'`define EQ_OUT_PATH "{os.path.join(out, "eq_out.txt")}"\n')
        f.write(f"`define EQ_N {len(rx)}\n")
    print(f"  case {case}: {len(rx)} subcarriers, "
          f"|H|q12 {int(np.min(np.abs(h[:,0]+1j*h[:,1]))):d}.."
          f"{int(np.max(np.abs(h[:,0]+1j*h[:,1]))):d}")


if __name__ == "__main__":
    main()
