"""Stimulus for the CP-strip + FFT test.

The RTL works on int16, so the golden float samples are scaled by
FULL_SCALE here -- in one place, as with the other blocks.

The FFT is LINEAR, and the core is configured UNSCALED (matching
openofdm, and matching numpy's own convention), so the expected output is
simply Python's FFT times the same FULL_SCALE factor. No transform-domain
scale factor to reconcile: that is the whole reason for choosing unscaled
over ofdm-hls's scale_sch=0xAA.

The input file carries the FULL slot -- cyclic prefix included -- because
stripping the CP at the wrong offset is the failure this test exists to
catch, and a CP-free input could not detect it.
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

FULL_SCALE = (1 << 15) - 1


def load_iq(path):
    v = []
    with open(path) as f:
        for line in f:
            p = line.split()
            if len(p) == 2:
                v.append((float(p[0]), float(p[1])))
    return np.array(v, dtype=np.float64)


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    case = sys.argv[1] if len(sys.argv) > 1 else "fft_s07"
    src = os.path.normpath(os.path.join(here, "..", "golden", case))
    out = os.path.join(here, "build")
    os.makedirs(out, exist_ok=True)

    with open(os.path.join(src, "fft_meta.json")) as f:
        meta = json.load(f)

    sym = load_iq(os.path.join(src, "fft_in.txt"))
    scaled = sym * FULL_SCALE
    code = np.where(scaled >= 0, np.floor(scaled + 0.5), np.ceil(scaled - 0.5))
    code = np.clip(code, -32768, 32767).astype(np.int64)
    with open(os.path.join(out, "fft_stimulus.hex"), "w") as f:
        for i, q in code:
            f.write(f"{((int(i) & 0xFFFF) << 16) | (int(q) & 0xFFFF):08x}\n")

    # Expected = numpy's unscaled FFT of the SAME int16 samples, so the
    # reference includes the input quantization the RTL also sees. Using
    # the float FFT instead would fold quantization noise into the
    # measured error and make a real bug harder to see.
    no_cp = code[meta["cp_len"]:]
    ref = np.fft.fft(no_cp[:, 0] + 1j * no_cp[:, 1])
    np.savetxt(os.path.join(out, "fft_ref.txt"),
               np.column_stack([ref.real, ref.imag]), fmt="%.4f")

    # ABSOLUTE paths. xsim runs in its own working directory
    # (build/fft_sim/fft_sim.sim/sim_1/behav/xsim), not where the sources
    # live, so a relative path silently resolves somewhere else --
    # $readmemh warns and carries on with an all-zero array, which is the
    # worst kind of failure. Verilator has the same hazard from a
    # different cwd. Absolute paths are correct in both.
    with open(os.path.join(out, "fft_params.vh"), "w") as f:
        f.write(f"// GENERATED by hls/rtl/gen_fft_stimulus.py from {case}\n")
        f.write(f'`define FFT_STIM_PATH "{os.path.join(out, "fft_stimulus.hex")}"\n')
        f.write(f'`define FFT_OUT_PATH "{os.path.join(out, "fft_out.txt")}"\n')
        f.write(f"`define FFT_N_IN {len(code)}\n")
        f.write(f"`define FFT_N_OUT {meta['n_out']}\n")
        f.write(f"`define FFT_SIZE {meta['fft_size']}\n")
        f.write(f"`define FFT_CP_LEN {meta['cp_len']}\n")

    print(f"  case {case}: {len(code)} in -> {meta['n_out']} out  "
          f"in_peak={np.max(np.abs(code)):.0f}  "
          f"ref_peak={np.max(np.abs(ref)):.0f}")


if __name__ == "__main__":
    main()
