"""Stimulus for one de-interleaver case."""
from __future__ import annotations
import json, os, sys


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    k = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    src = os.path.normpath(os.path.join(here, "..", "golden", "deint",
                                        "deint_cases.json"))
    with open(src) as f:
        d = json.load(f)
    c = d["cases"][k]
    out = os.path.join(here, "build"); os.makedirs(out, exist_ok=True)

    with open(os.path.join(out, "deint_stim.hex"), "w") as f:
        for b in c["interleaved"]:
            f.write(f"{b:02x}\n")
    with open(os.path.join(out, "deint_ref.txt"), "w") as f:
        for b in c["original"]:
            f.write(f"{b}\n")
    with open(os.path.join(out, "deint_tb_params.vh"), "w") as f:
        f.write(f"// GENERATED by gen_deint_stimulus.py, case {k}\n")
        f.write(f'`define DI_STIM_PATH "{os.path.join(out, "deint_stim.hex")}"\n')
        f.write(f'`define DI_OUT_PATH "{os.path.join(out, "deint_out.txt")}"\n')
        f.write(f"`define DI_N {c['n_units']}\n")
        f.write(f"`define DI_ROWS {c['rows']}\n")
        f.write(f"`define DI_COLS {c['cols']}\n")
    print(f"  case {k}: n_units={c['n_units']} M={c['rows']} N={c['cols']}")


if __name__ == "__main__":
    main()
